[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "function add_round_eval_row(config)"
position = "after"
payload = '''
    local isFunnyMoney = config.isFunnyMoney or false
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = """
if ret then
                i = i+1
                add_round_eval_row({dollars = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card})
                pitch = pitch + 0.06
                dollars = dollars + ret
            end
"""
position = "at"
payload = '''
if ret then
    print("3xJ | cashout.toml | Ret Type: " .. type(ret))
    if type(ret) == "table" then
        print("3xJ | cashout.toml | Ret First Variable " .. ret[1])
        print("3xJ | cashout.toml | Ret Second Variable " .. tostring(ret[2]))
        if ret[2] then
            print("3xJ | cashout.toml | Is a table, Detected")
            i = i+1
            add_round_eval_row({dollars = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card, isFunnyMoney = true,})
            pitch = pitch + 0.06
            dollars = dollars * ret[1]
        end
    else
        print("3xJ | cashout.toml | Is NOT a table, undetected")
        i = i+1
        add_round_eval_row({dollars = ret, bonus = true, name='joker'..i, pitch = pitch, card = _card})
        pitch = pitch + 0.06
        dollars = dollars + ret
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if num_dollars > 60 or num_dollars < -60 then"
position = "at"
payload = '''
print("3xJ | cashout.toml | Funny Money Testing")
if isFunnyMoney then

    print("3xJ | cashout.toml | FUNNY MONEY DETECTED!!!!!!")

    G.E_MANAGER:add_event(Event({
        trigger = 'before',delay = 0.38,
        func = function()
            G.round_eval:add_child(
                    {n=G.UIT.R, config={align = "cm", id = 'dollar_row_'..(dollar_row+1)..'_'..config.name}, nodes={
                        {n=G.UIT.O, config={object = DynaText({string = {localize('$').. "X" .. num_dollars[1]}, colours = {G.C.MONEY}, shadow = true, pop_in = 0, scale = 0.65, float = true})}}
                    }},
                    G.round_eval:get_UIE_by_ID('dollar_'..config.name))

            play_sound('coin3', 0.9+0.2*math.random(), 0.7)
            play_sound('coin6', 1.3, 0.8)
            return true
        end
    }))

elseif num_dollars > 60 or num_dollars < -60 then
    print("3xJ | cashout.toml | FUNNY MONEY NOT DETECTED!!!!!!")
'''
match_indent = true